# Generated by Django 3.2 on 2021-07-15 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('question_en', models.CharField(max_length=250, null=True)),
                ('question_de', models.CharField(max_length=250, null=True)),
                ('question_bg', models.CharField(max_length=250, null=True)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('answer', models.TextField()),
                ('answer_en', models.TextField(null=True)),
                ('answer_de', models.TextField(null=True)),
                ('answer_bg', models.TextField(null=True)),
                ('featured', models.BooleanField(default=False)),
                ('date_create', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
