# Generated by Django 3.2 on 2021-07-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_remove_faq_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='content',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='content_bg',
            new_name='answer_bg',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='content_de',
            new_name='answer_de',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='content_en',
            new_name='answer_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title_bg',
            new_name='question_bg',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title_de',
            new_name='question_de',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title_en',
            new_name='question_en',
        ),
    ]
