# Generated by Django 3.2 on 2021-07-15 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('name_de', models.CharField(max_length=250, null=True)),
                ('name_bg', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('name_en', models.CharField(max_length=250, null=True)),
                ('name_de', models.CharField(max_length=250, null=True)),
                ('name_bg', models.CharField(max_length=250, null=True)),
                ('img', models.ImageField(upload_to='category_pic')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', related_query_name='category', to='category.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.DateField(verbose_name='birth_day')),
                ('gender', models.CharField(choices=[('Femail', 'Femail'), ('Male', 'Male')], max_length=50, verbose_name='gender')),
                ('driving_license', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='driving_license')),
                ('first_lang', models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Russian', 'Russian')], max_length=20, verbose_name='first_lang')),
                ('first_lang_level', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50, verbose_name='first_lang_level')),
                ('second_lang', models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Russian', 'Russian')], max_length=20, verbose_name='second_lang')),
                ('second_lang_level', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50, verbose_name='second_lang_level')),
                ('third_lang', models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Russian', 'Russian')], max_length=20, verbose_name='third_lang')),
                ('third_lang_level', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50, verbose_name='third_lang_level')),
                ('ready_to_start', models.DateField(verbose_name='ready_to_start')),
                ('expectet_salary', models.CharField(blank=True, max_length=20, verbose_name='expectet_salary')),
                ('sertificate_1', models.ImageField(blank=True, upload_to='cv_sertificate', verbose_name='sertificate_1')),
                ('sertificate_2', models.ImageField(blank=True, upload_to='cv_sertificate', verbose_name='sertificate_2')),
                ('country_1', models.CharField(choices=[('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Switzerland', 'Switzerland'), ('Poland', 'Poland'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Bulgaria', 'Bulgaria'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Norway', 'Norway'), ('Czechia', 'Czechia'), ('Irland', 'Irland'), ('Romania', 'Romania'), ('Cyprus', 'Cyprus'), ('Slovenia', 'Slovenia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Russian Federation', 'Russian Federation'), ('Not Europe', 'Not Europe')], max_length=50, verbose_name='country_1')),
                ('company_name_1', models.CharField(max_length=50, verbose_name='company_name_1')),
                ('position_1', models.CharField(choices=[('Position I aplly', 'Position I apply'), ('Different', 'Different')], default='Position I aplly', max_length=150, verbose_name='position_1')),
                ('start_date_1', models.DateField(verbose_name='start_date_1')),
                ('end_date_1', models.DateField(verbose_name='end_date_1')),
                ('country_2', models.CharField(choices=[('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Switzerland', 'Switzerland'), ('Poland', 'Poland'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Bulgaria', 'Bulgaria'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Norway', 'Norway'), ('Czechia', 'Czechia'), ('Irland', 'Irland'), ('Romania', 'Romania'), ('Cyprus', 'Cyprus'), ('Slovenia', 'Slovenia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Russian Federation', 'Russian Federation'), ('Not Europe', 'Not Europe')], max_length=50, verbose_name='country_2')),
                ('company_name_2', models.CharField(max_length=50, verbose_name='company_name_2')),
                ('position_2', models.CharField(choices=[('Position I aplly', 'Position I apply'), ('Different', 'Different')], default='Position I aplly', max_length=150, verbose_name='position_2')),
                ('start_date_2', models.DateField(verbose_name='start_date_2')),
                ('end_date_2', models.DateField(verbose_name='end_date_2')),
                ('country_3', models.CharField(choices=[('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Switzerland', 'Switzerland'), ('Poland', 'Poland'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Bulgaria', 'Bulgaria'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Norway', 'Norway'), ('Czechia', 'Czechia'), ('Irland', 'Irland'), ('Romania', 'Romania'), ('Cyprus', 'Cyprus'), ('Slovenia', 'Slovenia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Russian Federation', 'Russian Federation'), ('Not Europe', 'Not Europe')], max_length=50, verbose_name='country_3')),
                ('company_name_3', models.CharField(max_length=50, verbose_name='company_name_3')),
                ('position_3', models.CharField(choices=[('Position I aplly', 'Position I apply'), ('Different', 'Different')], default='Position I aplly', max_length=150, verbose_name='position_3')),
                ('start_date_3', models.DateField(verbose_name='start_date_3')),
                ('end_date_3', models.DateField(verbose_name='end_date_3')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('employ', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('address', models.CharField(max_length=250, verbose_name='address_order')),
                ('workers_number', models.CharField(max_length=10, verbose_name='workers_number')),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('submit_date', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_titlle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='category.subcategory')),
            ],
        ),
    ]
