# Generated by Django 3.2 on 2021-07-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv_img',
            field=models.ImageField(default='default.jpeg', upload_to='cv/%Y/%m/%d/', verbose_name='cv_img'),
        ),
    ]
