# Generated by Django 3.2 on 2021-07-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_cv_cv_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv_img',
            field=models.ImageField(default='default.jpeg', upload_to='cv/username/%Y/%m/%d/', verbose_name='cv_img'),
        ),
    ]
