# Generated by Django 3.2 on 2021-06-20 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_companyorder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyorder',
            name='job_titlle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='category.subcategory'),
        ),
    ]
