# Generated by Django 3.2 on 2021-07-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20210726_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cat_b',
            field=models.BooleanField(blank=True, null=True, verbose_name='cat_b'),
        ),
    ]
