# Generated by Django 3.2 on 2021-06-21 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_companyorder_job_titlle'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyorder',
            name='submit_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
