# Generated by Django 3.2 on 2021-07-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_cv_cat_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='cat_b',
        ),
        migrations.AddField(
            model_name='cv',
            name='driving_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='_category_cv_driving_category_+', to='category.Cv'),
        ),
    ]
