# Generated by Django 3.2 on 2021-06-22 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0005_auto_20210621_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.DateField()),
                ('gender', models.CharField(choices=[('Femail', 'Femail'), ('Male', 'Male')], max_length=50)),
                ('driving_license', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('lang1', models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Turkish', 'Turkish'), ('Russian', 'Russian')], max_length=20)),
                ('lang1_level', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50)),
                ('lang2', models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Turkish', 'Turkish'), ('Russian', 'Russian')], max_length=20)),
                ('lang2_level', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50)),
                ('lang3', models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Turkish', 'Turkish'), ('Russian', 'Russian')], max_length=20)),
                ('lang3_level', models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50)),
                ('ready_to_start', models.DateField()),
                ('sertificate1', models.ImageField(blank=True, upload_to='cv_sertificate')),
                ('country1', models.CharField(choices=[('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Switzerland', 'Switzerland'), ('Poland', 'Poland'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Bulgaria', 'Bulgaria'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Norway', 'Norway'), ('Czechia', 'Czechia'), ('Irland', 'Irland'), ('Romania', 'Romania'), ('Cyprus', 'Cyprus'), ('Slovenia', 'Slovenia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Russian Federation', 'Russian Federation'), ('Not Europe', 'Not Europe')], max_length=50)),
                ('company_name1', models.CharField(max_length=50)),
                ('start_date1', models.DateField()),
                ('end_date1', models.DateField()),
                ('country2', models.CharField(choices=[('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Switzerland', 'Switzerland'), ('Poland', 'Poland'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Bulgaria', 'Bulgaria'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Norway', 'Norway'), ('Czechia', 'Czechia'), ('Irland', 'Irland'), ('Romania', 'Romania'), ('Cyprus', 'Cyprus'), ('Slovenia', 'Slovenia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Russian Federation', 'Russian Federation'), ('Not Europe', 'Not Europe')], max_length=50)),
                ('company_name2', models.CharField(max_length=50)),
                ('start_date2', models.DateField()),
                ('end_date2', models.DateField()),
                ('country3', models.CharField(choices=[('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Switzerland', 'Switzerland'), ('Poland', 'Poland'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Bulgaria', 'Bulgaria'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Norway', 'Norway'), ('Czechia', 'Czechia'), ('Irland', 'Irland'), ('Romania', 'Romania'), ('Cyprus', 'Cyprus'), ('Slovenia', 'Slovenia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Russian Federation', 'Russian Federation'), ('Not Europe', 'Not Europe')], max_length=50)),
                ('company_name3', models.CharField(max_length=50)),
                ('start_date3', models.DateField()),
                ('end_date3', models.DateField()),
                ('employ', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
