# Generated by Django 3.2 on 2021-06-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='company_name1',
            new_name='company_name_1',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='company_name3',
            new_name='company_name_3',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='country1',
            new_name='country_1',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='country2',
            new_name='country_2',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='country3',
            new_name='country_3',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='end_date1',
            new_name='end_date_1',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='end_date2',
            new_name='end_date_2',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='end_date3',
            new_name='end_date_3',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='lang1',
            new_name='first_lang',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='lang1_level',
            new_name='first_lang_level',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='lang2',
            new_name='second_lang',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='lang2_level',
            new_name='second_lang_level',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='sertificate1',
            new_name='sertificate_1',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='start_date1',
            new_name='start_date_1',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='start_date2',
            new_name='start_date_2',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='start_date3',
            new_name='start_date_3',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='lang3',
            new_name='third_lang',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='lang3_level',
            new_name='third_lang_level',
        ),
        migrations.AddField(
            model_name='cv',
            name='sertificate_2',
            field=models.ImageField(blank=True, upload_to='cv_sertificate'),
        ),
    ]
