# Generated by Django 3.2 on 2021-06-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20210622_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='company_name2',
            new_name='company_name_2',
        ),
    ]
