# Generated by Django 3.2 on 2021-06-29 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_rename_company_name2_cv_company_name_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='submit_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
