# Generated by Django 3.2 on 2021-06-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_cv_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='expectet_salary',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
