# Generated by Django 3.2 on 2021-07-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20210731_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='driving_category',
        ),
        migrations.AddField(
            model_name='cv',
            name='driving_category',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('B1', 'B1'), ('C', 'C'), ('C1', 'C1'), ('D', 'D'), ('D1', 'D1'), ('BE', 'BE'), ('C1E', 'C1E'), ('CE', 'CE'), ('D1E', 'D1E'), ('DE', 'DE')], max_length=10, verbose_name='driving_category'),
        ),
    ]
