# Generated by Django 3.2 on 2021-07-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20210701_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyorder',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
