# Generated by Django 3.2 on 2021-07-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20210702_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='driving_license_bg',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='driving_license_de',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='driving_license_en',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='first_lang_bg',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Turkish', 'Turkish'), ('Russian', 'Russian')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='first_lang_de',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Turkish', 'Turkish'), ('Russian', 'Russian')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='first_lang_en',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Turkish', 'Turkish'), ('Russian', 'Russian')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='first_lang_level_bg',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='first_lang_level_de',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='first_lang_level_en',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='gender_bg',
            field=models.CharField(choices=[('Femail', 'Femail'), ('Male', 'Male')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='gender_de',
            field=models.CharField(choices=[('Femail', 'Femail'), ('Male', 'Male')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='gender_en',
            field=models.CharField(choices=[('Femail', 'Femail'), ('Male', 'Male')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_bg',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_de',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
