# Generated by Django 3.2 on 2021-07-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_auto_20210708_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='driving_license_bg',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='driving_license_de',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='driving_license_en',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='first_lang_bg',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='first_lang_de',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='first_lang_en',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='first_lang_level_bg',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='first_lang_level_de',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='first_lang_level_en',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='gender_bg',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='gender_de',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='gender_en',
        ),
    ]
