# Generated by Django 3.2 on 2021-07-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_alter_cv_driving_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='driving_category',
            field=models.CharField(blank=True, max_length=20, verbose_name='driving_category'),
        ),
    ]
