# Generated by Django 3.2 on 2021-08-03 14:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_alter_cv_driving_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='driving_category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('B', 'B'), ('B1', 'B1'), ('C', 'C'), ('C1', 'C1'), ('D', 'D'), ('D1', 'D1'), ('BE', 'BE'), ('C1E', 'C1E'), ('CE', 'CE'), ('D1E', 'D1E'), ('DE', 'DE')], max_length=31, verbose_name='driving_category'),
        ),
    ]
