# Generated by Django 3.2 on 2021-07-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_alter_cv_country_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='country_1',
            field=models.CharField(choices=[('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Switzerland', 'Switzerland'), ('Poland', 'Poland'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Bulgaria', 'Bulgaria'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Norway', 'Norway'), ('Czechia', 'Czechia'), ('Irland', 'Irland'), ('Romania', 'Romania'), ('Cyprus', 'Cyprus'), ('Slovenia', 'Slovenia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Russian Federation', 'Russian Federation'), ('Not Europe', 'Not Europe')], max_length=50, verbose_name='country_1'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='gender',
            field=models.CharField(choices=[('Femail', 'Femail'), ('Male', 'Male')], max_length=50, verbose_name='gender'),
        ),
    ]
