# Generated by Django 3.2 on 2021-07-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_auto_20210709_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyorder',
            name='address',
            field=models.CharField(max_length=250, verbose_name='address_order'),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='country',
            field=models.CharField(max_length=100, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='end_date',
            field=models.DateField(verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
        migrations.AlterField(
            model_name='companyorder',
            name='workers_number',
            field=models.CharField(max_length=10, verbose_name='workers_number'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='birth_day',
            field=models.DateField(verbose_name='birth_day'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='company_name_1',
            field=models.CharField(max_length=50, verbose_name='company_name_1'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='company_name_2',
            field=models.CharField(max_length=50, verbose_name='company_name_2'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='company_name_3',
            field=models.CharField(max_length=50, verbose_name='company_name_3'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='country_2',
            field=models.CharField(choices=[('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Switzerland', 'Switzerland'), ('Poland', 'Poland'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Bulgaria', 'Bulgaria'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Norway', 'Norway'), ('Czechia', 'Czechia'), ('Irland', 'Irland'), ('Romania', 'Romania'), ('Cyprus', 'Cyprus'), ('Slovenia', 'Slovenia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Russian Federation', 'Russian Federation'), ('Not Europe', 'Not Europe')], max_length=50, verbose_name='country_2'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='country_3',
            field=models.CharField(choices=[('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Switzerland', 'Switzerland'), ('Poland', 'Poland'), ('Greece', 'Greece'), ('Sweden', 'Sweden'), ('Bulgaria', 'Bulgaria'), ('Belgium', 'Belgium'), ('Austria', 'Austria'), ('Hungary', 'Hungary'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Norway', 'Norway'), ('Czechia', 'Czechia'), ('Irland', 'Irland'), ('Romania', 'Romania'), ('Cyprus', 'Cyprus'), ('Slovenia', 'Slovenia'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Russian Federation', 'Russian Federation'), ('Not Europe', 'Not Europe')], max_length=50, verbose_name='country_3'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='driving_license',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, verbose_name='driving_license'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='end_date_1',
            field=models.DateField(verbose_name='end_date_1'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='end_date_2',
            field=models.DateField(verbose_name='end_date_2'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='end_date_3',
            field=models.DateField(verbose_name='end_date_3'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='expectet_salary',
            field=models.CharField(blank=True, max_length=20, verbose_name='expectet_salary'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='first_lang',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Turkish', 'Turkish'), ('Russian', 'Russian')], max_length=20, verbose_name='first_lang'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='first_lang_level',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50, verbose_name='first_lang_level'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='position_1',
            field=models.CharField(choices=[('Position I aplly', 'Position I apply'), ('Different', 'Different')], default='Position I aplly', max_length=150, verbose_name='position_1'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='position_2',
            field=models.CharField(choices=[('Position I aplly', 'Position I apply'), ('Different', 'Different')], default='Position I aplly', max_length=150, verbose_name='position_2'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='position_3',
            field=models.CharField(choices=[('Position I aplly', 'Position I apply'), ('Different', 'Different')], default='Position I aplly', max_length=150, verbose_name='position_3'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='ready_to_start',
            field=models.DateField(verbose_name='ready_to_start'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='second_lang',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Turkish', 'Turkish'), ('Russian', 'Russian')], max_length=20, verbose_name='second_lang'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='second_lang_level',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50, verbose_name='second_lang_level'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='sertificate_1',
            field=models.ImageField(blank=True, upload_to='cv_sertificate', verbose_name='sertificate_1'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='sertificate_2',
            field=models.ImageField(blank=True, upload_to='cv_sertificate', verbose_name='sertificate_2'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='start_date_1',
            field=models.DateField(verbose_name='start_date_1'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='start_date_2',
            field=models.DateField(verbose_name='start_date_2'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='start_date_3',
            field=models.DateField(verbose_name='start_date_3'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='third_lang',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Turkish', 'Turkish'), ('Russian', 'Russian')], max_length=20, verbose_name='third_lang'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='third_lang_level',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Fluent', 'Fluent')], max_length=50, verbose_name='third_lang_level'),
        ),
    ]
