# Generated by Django 3.2 on 2021-07-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0018_auto_20210709_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='first_lang',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Russian', 'Russian')], max_length=20, verbose_name='first_lang'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='second_lang',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Russian', 'Russian')], max_length=20, verbose_name='second_lang'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='third_lang',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Spanish', 'Spanish'), ('Russian', 'Russian')], max_length=20, verbose_name='third_lang'),
        ),
    ]
