# Generated by Django 3.2 on 2021-07-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumeuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='company_pics', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pics', verbose_name='image'),
        ),
    ]
