# Generated by Django 3.2 on 2021-06-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumeuser', '0008_auto_20210614_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to='company_pics'),
        ),
    ]
