# Generated by Django 3.2 on 2021-06-18 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumeuser', '0009_alter_company_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='adrress',
            new_name='address',
        ),
    ]
