# Generated by Django 3.2 on 2021-07-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumeuser', '0010_rename_adrress_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='first_name_bg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='first_name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='first_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name_bg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name_de',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_bg',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_de',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_en',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
