# Generated by Django 3.2 on 2021-07-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumeuser', '0011_auto_20210706_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_bg',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_de',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_en',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_bg',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_de',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_en',
            field=models.CharField(max_length=128, null=True, verbose_name='password'),
        ),
    ]
