# Generated by Django 3.2 on 2021-07-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costumeuser', '0019_auto_20210712_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address_bg',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_de',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_name_bg',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_name_de',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_name_en',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_bg',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_de',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_en',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='first_name_bg',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='first_name_de',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name_bg',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name_de',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='phone_bg',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='phone_de',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='phone_en',
        ),
    ]
