# Generated by Django 3.2 on 2021-07-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumeuser', '0020_auto_20210712_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(help_text='company_name', max_length=150),
        ),
    ]
