# Generated by Django 3.2 on 2021-07-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumeuser', '0021_alter_company_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=150, verbose_name='company_name'),
        ),
    ]
